/*******************************************************************************
 * Copyright 2016 Gabriela D. A. Guardia
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at

 *    http://www.apache.org/licenses/LICENSE-2.0

 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.01 at 02:32:00 PM BRST 
//

package semanticsco.interactions.discoverinputsemantics;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RootConcept" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OntologyURI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rootConcept",
    "ontologyURI"
})
@XmlRootElement(name = "DiscoverInputSemanticsRequest")
public class DiscoverInputSemanticsRequest {

    @XmlElement(name = "RootConcept", required = true)
    protected String rootConcept;
    @XmlElement(name = "OntologyURI", required = true)
    protected String ontologyURI;

    /**
     * Gets the value of the rootConcept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootConcept() {
        return rootConcept;
    }

    /**
     * Sets the value of the rootConcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootConcept(String value) {
        this.rootConcept = value;
    }

    /**
     * Gets the value of the ontologyURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOntologyURI() {
        return ontologyURI;
    }

    /**
     * Sets the value of the ontologyURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOntologyURI(String value) {
        this.ontologyURI = value;
    }

}
