/*******************************************************************************
 * Copyright 2016 Gabriela D. A. Guardia
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at

 *    http://www.apache.org/licenses/LICENSE-2.0

 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 03:08:21 PM BRT 
//

package semanticsco.interactions.basictypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InputToValidate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InputToValidate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InputID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InputedValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataSemantics" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataSyntax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InputToValidate", propOrder = {
    "inputID",
    "inputedValue",
    "dataSemantics",
    "dataSyntax"
})
public class InputToValidate {

    @XmlElement(name = "InputID", required = true)
    protected String inputID;
    @XmlElement(name = "InputedValue", required = true)
    protected String inputedValue;
    @XmlElement(name = "DataSemantics", required = true)
    protected String dataSemantics;
    @XmlElement(name = "DataSyntax", required = true)
    protected String dataSyntax;

    /**
     * Gets the value of the inputID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputID() {
        return inputID;
    }

    /**
     * Sets the value of the inputID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputID(String value) {
        this.inputID = value;
    }

    /**
     * Gets the value of the inputedValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputedValue() {
        return inputedValue;
    }

    /**
     * Sets the value of the inputedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputedValue(String value) {
        this.inputedValue = value;
    }

    /**
     * Gets the value of the dataSemantics property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSemantics() {
        return dataSemantics;
    }

    /**
     * Sets the value of the dataSemantics property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSemantics(String value) {
        this.dataSemantics = value;
    }

    /**
     * Gets the value of the dataSyntax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSyntax() {
        return dataSyntax;
    }

    /**
     * Sets the value of the dataSyntax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSyntax(String value) {
        this.dataSyntax = value;
    }

}
