/*******************************************************************************
 * Copyright 2016 Gabriela D. A. Guardia
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at

 *    http://www.apache.org/licenses/LICENSE-2.0

 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 03:08:21 PM BRT 
//

package semanticsco.interactions.basictypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResolvingServiceMatching complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResolvingServiceMatching">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServiceIDMatching" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InputMatching" type="{http://semanticsco/interactions/BasicTypes}InputMatching" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResolvingServiceMatching", propOrder = {
    "serviceIDMatching",
    "inputMatching"
})
public class ResolvingServiceMatching {

    @XmlElement(name = "ServiceIDMatching", required = true)
    protected String serviceIDMatching;
    @XmlElement(name = "InputMatching", required = true)
    protected List<InputMatching> inputMatching;

    /**
     * Gets the value of the serviceIDMatching property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceIDMatching() {
        return serviceIDMatching;
    }

    /**
     * Sets the value of the serviceIDMatching property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceIDMatching(String value) {
        this.serviceIDMatching = value;
    }

    /**
     * Gets the value of the inputMatching property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputMatching property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputMatching().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InputMatching }
     * 
     * 
     */
    public List<InputMatching> getInputMatching() {
        if (inputMatching == null) {
            inputMatching = new ArrayList<InputMatching>();
        }
        return this.inputMatching;
    }

}
