/*******************************************************************************
 * Copyright 2016 Gabriela D. A. Guardia
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at

 *    http://www.apache.org/licenses/LICENSE-2.0

 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 03:08:21 PM BRT 
//

package jaxbClasses.basictypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IncludedServiceStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncludedServiceStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncludedServiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IncludedServiceFunction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncludedServiceStructure", propOrder = {
    "includedServiceID",
    "includedServiceFunction"
})
public class IncludedServiceStructure {

    @XmlElement(name = "IncludedServiceID", required = true)
    protected String includedServiceID;
    @XmlElement(name = "IncludedServiceFunction", required = true)
    protected String includedServiceFunction;

    /**
     * Gets the value of the includedServiceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludedServiceID() {
        return includedServiceID;
    }

    /**
     * Sets the value of the includedServiceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludedServiceID(String value) {
        this.includedServiceID = value;
    }

    /**
     * Gets the value of the includedServiceFunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludedServiceFunction() {
        return includedServiceFunction;
    }

    /**
     * Sets the value of the includedServiceFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludedServiceFunction(String value) {
        this.includedServiceFunction = value;
    }

}
